version: '3.9'

services:
  backend:
    container_name: weather_app
    ports:
      - "3000:3000"
    build: 
      context: .
    networks:
      - backend
    env_file: .env
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      WEATHER_API_KEY: ${WEATHER_API_KEY}  

    deploy:  # works only with swarm ie "docker stack deploy"
      replicas: 3  
      restart_policy:
        condition: on-failure

networks:
  backend:
      